apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
spec:
  storageClassName: managed-nfs-storage
  accessModes:
   - ReadWriteMany
  resources:
   requests:
    storage: 3Gi
